### ISSUE TITLE
Futuro problema con la resta de nivel 

### ISSUE THREAD

**Issue by bypipe27** [Svaldes77/Mini_Proyecto#6]
Compañeros tener en cuenta como vamos a hacer para la resta de nivel.  Asociado con la parte de los regaños.

**Comment by Svaldes77** [comment]
ya me he encargado y lo pude resolver

**Comment by Santy826** [comment]
Actualmente, dentro del sistema de regaños implementado en la clase Coronel, los soldados pueden recibir regaños, pero no existe un mecanismo para ajustar su nivel en consecuencia. Esta funcionalidad es clave para reflejar las consecuencias jerárquicas dentro del sistema militar simulado.
